export default {
  // Services: 'Services',
  // Birthday: 'Birthday',
  // ThisWeekActivity: 'This Week Activity',
  // HelpFeedback: 'Help & Feedback',
  // MyProfile: 'My Profile',
  // CustomerProfile: ' Customer Profile',
  // VCPL: 'VCPL',
  // Home: 'Home',
  // Mobile: 'Mobile',
  // RegNo: 'Reg No',
  // LastOilChange: 'Last Oil Change',
  // DOB: 'Date of Birth',
  // Valvoline: 'Valvoline',
  // Products: 'Products',
  // Offers: 'Offers',
  // Training: 'Training',
  // Logout: 'Logout',
  // YearlyTarget: 'Yearly Target',
  // YTDActual: 'YTD Actual',
  // Ltr: 'Ltr',
  // CustomerRating: 'Customer Rating',
  // AddNewCustomer: 'Add New Customer',
  // Search: 'Search',
  Add: 'Add',
  // Customer: 'Customer',
  Pleaseenteryourvalidmobilenumberandpassword: 'Please enter Your valid mobile number and password',
  // CustomerName: 'Customer Name',
  // DCustomerName: 'Customer Name *',
  // Thisfieldisrequired: 'This field is required *',
  KMobile: 'Mobile No. *',
  KRMobile:'Mobile No.',
  // Address: 'Address',
  // Edit: 'Edit',
  // CustomerDetail: 'Customer Detail',
  // AllServices: 'All Services',
  // Date: 'Date',
  // ServiceType: 'Service Type *',
  // Feedback: 'Feedback',
  // AddVehicle: 'Add Vehicle',
  // AddService: 'Add Service',
  // Addvehicle: 'Add vehicle',
  // EditVehicle: 'Edit Vehicle',
  // VehicleRegNo: 'Vehicle Reg No. *',
  // SelectBrand: 'Select Brand',
  // Invalidregistrationnumber: 'Invalid registration number *',
  // SelectModel: 'Select Model',
  // Update: 'Update',
  // UpdateService: 'Update Service',
  // DServiceType: 'ServiceType',
  // Product: 'Product ',
  // ServiceDate: 'Service Date',
  // TimeEstimate: 'Time Estimate',
  // CostEstimate: 'Cost Estimate (Rs.)',
  // ServiceStatus: 'Service Status',
  // NextOilChange: 'Next Oil Change',
  // Status: 'Status',
  // VehicleNo: 'Reg No',
  // Save: 'Save',
  // Help: 'Help',
  // Repeat: 'Repeat',
  // RequestSubject: 'Request Subject',
  // RequestStatus: 'Request Status',
  // RequestDate: 'Request Date',
  // RequestResolution: 'Request Resolution',
  // CloneRequest: 'Clone Request',
  // CreateRequest: 'Create Request',
  PleaseEnterYourDetail: 'Please Enter Your Details',
  // Requesttype: 'Request type *',
  // RequestDescription: 'Request Description ',
  // RequestSubmit: 'Request Submit',
  // Ratings: 'Ratings',
  LOGIN: 'LOGIN',
  // RequestOTP: 'Request OTP',
  // TermsConditions: 'Terms & Conditions',
  // EnterOTP: 'Enter OTP',
  // ResendOTP: 'Resend - OTP',
  // Submit: 'Submit',
  // OTP: 'Enter OTP *',
  // AddCustomerProfile: 'Add Customer Profile',
  // EditCustomerProfile: 'Edit Customer Profile',
  // Update: 'Update',
  // MobNo: 'Mob No',
  // Currentlanguage: 'Current language',
  // Language: 'English',
  // ServiceType: 'Service Type',
  // ChooseLanguage: 'Choose Language',
  // PLATINUM: 'PLATINUM',
  // GOLD: 'GOLD',
  // Noservicesfoundforthisweek: 'No services found for this week',
  // Nobirthdayinthisweek: 'No birthday found in this week',
  // BikeExpert: 'Bike Xpert',
  // CarExpert: 'Car Xpert',
  // Nofeedbackfound: 'No feedback found',
  // CustomerAlreadyExist: 'Customer Already Exist',
  // ServerError: 'Server Error',
  // NocasesFound: 'No cases Found',
  // AddCustomer: 'Add Customer',
  // AddSer: 'Add Service',
  // NextDueDate: 'Last oil Change',
  // VehicleType: 'Vehicle Type',
  // comment: 'Comment',
  // Brand: 'Brand',
  // Model: 'Model',
  // ServiceCost: 'Service Cost',
  // nosearch: 'No Data found!',
  // closedservice: 'Closed Service',
  Profile:'Profile',
  All:'All',
  Government:'Government',
  Policy: 'Policy',
  List :'List',
  Show:'Show',
  Password:'Password',
  DonthaveanaccountRegister: "Don't have an account? Register",
  Registration:'Registration',
  Name:'Name',
  Fathersname :'Fathers name',
  Emailid:'Email ID',
  Address:'Address',
  SelectState:'Select State',
  SelectCity:'Select City',
  ConfirmPassword:'Confirm Password',
  UploadPicture:'Upload Picture',
  AlreadyRegisteredUserLogin:' Already Registered User? Login',
  Register:'Register',
  Pleaseentercorrectmobilepassword :'Please enter correct mobile/password',
  Kisan:'Kisan',
  Details:'Details',
  Farmers:'Farmers',
  Search:'Search',
  Organization:'Organization',
  Description:'Description',
  WebLink:'Web Link',
  VideoLink:'Video Link',
  Apply:'Apply',
  Id:'Id',
  Dateforapply:'Date for apply',
  Status:'Status',
  ChooseDate:'Choose Date',
  AllYourPolicies:'All Your Policies',
  PolicyName:'Policy Name',
  AlltheprofileofyourKisancanbeseenhere:'All the profile of your Kisan can be seen here',
  AlltheGovermentPolicyListofyourPolicycanbeseenhere :'All the Goverment Policy List of your Policy can be seen here',
  ShowPolicyList:'Show Policy List',
  AllYourPoliciescanbeseenhere :'All Your Policies can be seen here'
};
